/**
 * TypeScript type definitions
 * 
 * Most types are auto-generated by ts-rs from Rust structs.
 * Run `cargo test` in src-tauri to regenerate bindings.
 */

// ===== Re-export from ts-rs generated bindings =====
export type { ServerInfo } from '../../src-tauri/bindings/ServerInfo';
export type { AuthConfig } from '../../src-tauri/bindings/AuthConfig';
export type { AdvancedConnectionConfig } from '../../src-tauri/bindings/AdvancedConnectionConfig';
export type { AppConfig } from '../../src-tauri/bindings/AppConfig';
export type { StorageInfo } from '../../src-tauri/bindings/StorageInfo';
export type { PermissionStatus } from '../../src-tauri/bindings/PermissionStatus';
export type { ServerStartCheckResult } from '../../src-tauri/bindings/ServerStartCheckResult';
export type { ExifInfo } from '../../src-tauri/bindings/ExifInfo';
export type { ImageOpenMethod } from '../../src-tauri/bindings/ImageOpenMethod';
export type { PreviewWindowConfig } from '../../src-tauri/bindings/PreviewWindowConfig';

// ===== Manual type definitions =====
// These types are not generated by ts-rs or have differences from generated versions

/**
 * 服务器运行时状态
 * 
 * Note: This differs from generated ServerStateSnapshot which uses bigint for
 * filesReceived/bytesReceived. JSON serialization produces numbers, so we use
 * number type here for correctness.
 */
export interface ServerStatus {
  isRunning: boolean;
  connectedClients: number;
  filesReceived: number;
  bytesReceived: number;
  lastFile: string | null;
}

/**
 * 文件信息（用于文件浏览）
 * No corresponding Rust struct with ts-rs export.
 */
export interface FileInfo {
  path: string;
  filename: string;
}

// ===== Re-export from global.ts =====
export type { PermissionCheckResult } from './global';
export * from './global';
