/**
 * TypeScript type definitions
 * 
 * Most types are auto-generated by ts-rs from Rust structs.
 * Run `cargo test` in src-tauri to regenerate bindings.
 */

// ===== Re-export from ts-rs generated bindings =====
export type { ServerInfo } from '../../src-tauri/bindings/ServerInfo';
export type { ServerStateSnapshot } from '../../src-tauri/bindings/ServerStateSnapshot';
export type { AuthConfig } from '../../src-tauri/bindings/AuthConfig';
export type { AdvancedConnectionConfig } from '../../src-tauri/bindings/AdvancedConnectionConfig';
export type { AppConfig } from '../../src-tauri/bindings/AppConfig';
export type { StorageInfo } from '../../src-tauri/bindings/StorageInfo';
export type { PermissionStatus } from '../../src-tauri/bindings/PermissionStatus';
export type { ServerStartCheckResult } from '../../src-tauri/bindings/ServerStartCheckResult';
export type { ExifInfo } from '../../src-tauri/bindings/ExifInfo';
export type { ImageOpenMethod } from '../../src-tauri/bindings/ImageOpenMethod';
export type { PreviewWindowConfig } from '../../src-tauri/bindings/PreviewWindowConfig';

// ===== Internal imports for type aliases =====
import type { ServerStateSnapshot } from '../../src-tauri/bindings/ServerStateSnapshot';

// ===== Type aliases for backward compatibility =====
/**
 * ServerStatus is an alias for ServerStateSnapshot.
 * @deprecated Use ServerStateSnapshot directly for new code.
 */
export type ServerStatus = ServerStateSnapshot;

// ===== Manual type definitions =====
// These types are not generated by ts-rs

/**
 * 文件信息（用于文件浏览）
 * No corresponding Rust struct with ts-rs export.
 */
export interface FileInfo {
  path: string;
  filename: string;
}

// ===== Re-export from global.ts =====
export type { PermissionCheckResult } from './global';
export * from './global';
