// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthConfig } from "./AuthConfig";

/**
 * 高级连接配置
 */
export type AdvancedConnectionConfig = { 
/**
 * 是否启用高级连接配置
 */
enabled: boolean, 
/**
 * 认证配置
 */
auth: AuthConfig, };
