// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedConnectionConfig } from "./AdvancedConnectionConfig";
import type { PreviewWindowConfig } from "./PreviewWindowConfig";

export type AppConfig = { 
/**
 * 存储路径（桌面端可自定义，Android 端固定为 DCIM/CameraFTP）
 */
savePath: string, 
/**
 * FTP 端口
 */
port: number, 
/**
 * 自动选择端口
 */
autoSelectPort: boolean, 
/**
 * 高级连接配置
 */
advancedConnection: AdvancedConnectionConfig, 
/**
 * 预览窗口配置（仅 Windows 有效，其他平台为 None）
 */
previewConfig: PreviewWindowConfig | null, };
