// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 认证配置
 */
export type AuthConfig = { 
/**
 * 是否启用匿名访问
 */
anonymous: boolean, 
/**
 * 自定义用户名（匿名关闭时使用）
 */
username: string, 
/**
 * 密码哈希（Argon2id）
 */
passwordHash: string, 
/**
 * 密码盐值
 */
passwordSalt: string, };
