// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 自动调色配置
 */
export type AutoColorGradingConfig = { 
/**
 * 是否启用自动调色
 */
enabled: boolean, 
/**
 * 调色预设 ID
 */
presetId: string, 
/**
 * 曝光偏移量（EV），基于自动测光结果的偏移
 */
evOffset: number, 
/**
 * 自动曝光测光模式
 */
meteringMode: string, };
