// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 调色对话框上次使用的参数
 */
export type ColorGradingLastUsed = { 
/**
 * 调色预设 ID
 */
presetId: string, 
/**
 * 曝光偏移量（EV），基于自动测光结果的偏移
 */
evOffset: number, 
/**
 * 自动曝光测光模式
 */
meteringMode: string, };
