// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 权限状态
 */
export type PermissionStatus = { 
/**
 * 是否有"所有文件访问权限"
 */
hasAllFilesAccess: boolean, 
/**
 * 是否需要用户操作
 */
needsUserAction: boolean, };
