// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageOpenMethod } from "./ImageOpenMethod";

/**
 * 预览窗口配置
 */
export type PreviewWindowConfig = { enabled: boolean, method: ImageOpenMethod, 
/**
 * 自定义程序路径（仅当 method 为 Custom 时有效）
 */
customPath: string | null, autoBringToFront: boolean, };
