// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 服务器连接信息（用于前端显示）
 */
export type ServerInfo = { isRunning: boolean, ip: string, port: number, url: string, username: string, passwordInfo: string, };
