// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 存储路径信息
 */
export type StorageInfo = { 
/**
 * 显示名称
 */
displayName: string, 
/**
 * 完整文件系统路径
 */
path: string, 
/**
 * 路径是否存在
 */
exists: boolean, 
/**
 * 是否可写
 */
writable: boolean, 
/**
 * 是否有所有文件访问权限
 */
hasAllFilesAccess: boolean, };
