// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiEditProgressEvent = { "type": "progress", current: number, total: number, fileName: string, failedCount: number, } | { "type": "completed", current: number, total: number, fileName: string, failedCount: number, outputPath: string | null, } | { "type": "failed", current: number, total: number, fileName: string, error: string, failedCount: number, } | { "type": "done", total: number, failedCount: number, failedFiles: Array<string>, outputFiles: Array<string>, };
