// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AndroidImageOpenMethod } from "./AndroidImageOpenMethod";

/**
 * Android 图片查看器配置
 */
export type AndroidImageViewerConfig = { openMethod: AndroidImageOpenMethod, autoOpenLatestWhenVisible: boolean, };
