// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Android 图片打开方式
 */
export type AndroidImageOpenMethod = "built-in-viewer" | "external-app";
