// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewWindowConfig } from "./PreviewWindowConfig";

export type ConfigChangedEvent = { config: PreviewWindowConfig, };
