// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXIF 信息结构体
 */
export type ExifInfo = { iso: number | null, aperture: string | null, shutterSpeed: string | null, focalLength: string | null, datetime: string | null, };
