// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 图片打开方式枚举
 */
export type ImageOpenMethod = "built-in-preview" | "system-default" | "windows-photos" | "custom";
