// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerInfo } from "./ServerInfo";
import type { ServerStateSnapshot } from "./ServerStateSnapshot";

export type ServerRuntimeView = { serverInfo: ServerInfo | null, stats: ServerStateSnapshot, };
