// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageInfo } from "./StorageInfo";

/**
 * 服务器启动检查结果
 */
export type ServerStartCheckResult = { canStart: boolean, reason: string | null, storageInfo: StorageInfo | null, };
