// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 服务器运行时统计快照
 */
export type ServerStateSnapshot = { isRunning: boolean, connectedClients: number, 
/**
 * Use number instead of bigint for JSON serialization compatibility
 */
filesReceived: number, 
/**
 * Use number instead of bigint for JSON serialization compatibility
 */
bytesReceived: number, lastFile: string | null, };
